doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'mysql'
        server_version: 'mariadb-10.3.20'

        # Tabellen die niet in het schema zitten, maar toch niet weggegooid moeten worden.
        schema_filter: /^(?!(rememberme_token|groep|groeptype|bijbelrooster|bijbelrooster_old|geolocations|logaggregated|saldolog|soccie.*)$).*/

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
          date: CsrDelft\common\Doctrine\Type\DateImmutableType
          datetime: CsrDelft\common\Doctrine\Type\DateTimeImmutableType
          datetimetz: CsrDelft\common\Doctrine\Type\DateTimeTzImmutableType
          time: Doctrine\DBAL\Types\TimeImmutableType
          changelog: CsrDelft\common\Doctrine\Type\ChangeLogType
          groepkeuze: CsrDelft\common\Doctrine\Type\GroepKeuzeType
          groepkeuzeselectie: CsrDelft\common\Doctrine\Type\GroepKeuzeSelectieType
          longtext: CsrDelft\common\Doctrine\Type\LongTextType
          uid: CsrDelft\common\Doctrine\Type\UidType
          stringkey: CsrDelft\common\Doctrine\Type\StringKeyType
          enumOntvangtContactueel: CsrDelft\common\Doctrine\Type\OntvangtContactueelType
          enumBoekExemplaarStatus: CsrDelft\common\Doctrine\Type\BoekExemplaarStatusType
          enumCourantCategorie: CsrDelft\common\Doctrine\Type\CourantCategorieType
          enumForumDraadMeldingNiveau: CsrDelft\common\Doctrine\Type\ForumDraadMeldingNiveauType
          enumGroepStatus: CsrDelft\common\Doctrine\Type\GroepStatusType
          enumHuisStatus: CsrDelft\common\Doctrine\Type\HuisStatusType
          enumCommissieSoort: CsrDelft\common\Doctrine\Type\CommissieSoortType
          enumGeslacht: CsrDelft\common\Doctrine\Type\Enum\GeslachtType
          enumGroepVersie: CsrDelft\common\Doctrine\Type\GroepVersieType
        mapping_types:
          enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
          # Zie https://github.com/beberlei/DoctrineExtensions voor meer mooie extensies.
          string_functions:
            date: DoctrineExtensions\Query\Mysql\Date
            match: DoctrineExtensions\Query\Mysql\MatchAgainst
            unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp
            day: DoctrineExtensions\Query\Mysql\Day
            month: DoctrineExtensions\Query\Mysql\Month
            dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
            now: DoctrineExtensions\Query\Mysql\Now
            concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
            replace: DoctrineExtensions\Query\Mysql\Replace
            date_format: DoctrineExtensions\Query\Mysql\DateFormat
        mappings:
            CsrDelft:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/lib/entity'
                prefix: 'CsrDelft\entity'
                alias: App
        filters:
            verbergNovieten:
                class: CsrDelft\common\Doctrine\VerbergNovietenFilter
                enabled: false
                parameters:
                    jaar: 2020
