twig:
  default_path: '%kernel.project_dir%/templates'
  autoescape_service: CsrDelft\Twig\AutoEscapeService
  autoescape_service_method: guess
  globals:
    sentry_dsn: '%env(SENTRY_DSN_JS)%'
    email_abactis: '%env(EMAIL_ABACTIS)%'
    csrmail_password: '%env(CSRMAIL_PASSWORD)%'
    email_corvee: '%env(EMAIL_CC)%'
