version: '3'

volumes:
  mysqldata:
    driver: local

services:
  stek:
    build:
      context: .
      dockerfile: "docker/Dockerfile-stek"
    image: csrdelft/stek
    ports:
      - "8080:80" # Expose stek op poort 8080
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    volumes:
      - ./:/app
      - ./docker/dev/.env.local:/app/.env.local
      - ./vendor:/app/vendor

  composer:
    build:
      context: .
      dockerfile: "docker/Dockerfile-composer"
    image: csrdelft/composer
    command: install --ignore-platform-reqs # Doe initieel een install
    volumes:
      - ./:/app
      - ./docker/dev/.env.local:/app/.env.local
      - ./vendor:/app/vendor

  stekdb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: bl44t
      MYSQL_USER: csrdelft
      MYSQL_PASSWORD: bl44t
      MYSQL_DATABASE: csrdelft
    volumes:
      - mysqldata:/var/lib/mysql/
      - ./data:/docker-entrypoint-initdb.d # laad sql bestanden
    ports:
      - "3307:3306" # Expose mysql op poort 3307

  yarn:
    build:
      context: .
      dockerfile: "docker/Dockerfile-yarn"
    image: csrdelft/yarn
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.eslintrc.yaml:/app/.eslintrc.yaml
      - ./webpack.config.js:/app/webpack.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./htdocs/dist:/app/htdocs/dist # output
      - ./assets:/app/assets # input
