services:
  app.monolog.processor.web:
    class: CsrDelft\common\Logging\LogProcessor
    arguments: ["@request_stack", "@security.helper"]
    tags:
      - { name: monolog.processor, method: processRecord }
